import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { AppShell, ErrorLine, LoadingLine, PageTitle } from "@/components/AppShell";
import { Field, TextArea } from "@/components/Forms";
import { Pagination } from "@/components/Pagination";
import { demo } from "@/lib/demo";
import type { PaginatedResponse, Post } from "@/lib/api";
import { Protected, useDemoUser } from "@/components/AuthGuards";

export const Route = createFileRoute("/posts")({ validateSearch: (search: Record<string, unknown>) => ({ userId: typeof search["userId"] === "string" ? search["userId"] : undefined }), head: () => ({ meta: [{ title: "Posts — CipherNote" }, { name: "description", content: "Create and review your private CipherNote posts." }, { property: "og:title", content: "Posts — CipherNote" }, { property: "og:description", content: "Create and review your private CipherNote posts." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Posts });
function Posts() { const user = useDemoUser(); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [page, setPage] = useState(1); const [result, setResult] = useState<PaginatedResponse<Post> | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const load = () => { if (!user) return; setLoading(true); demo.posts(user._id, page).then(setResult).finally(() => setLoading(false)); }; useEffect(load, [user?._id, page]); async function submit(event: React.FormEvent) { event.preventDefault(); if (!title.trim() || !body.trim()) { setError("A title and body are required."); return; } await demo.createPost({ title, body }); setTitle(""); setBody(""); setError(""); load(); } return <Protected><AppShell area="user"><PageTitle eyebrow="PERSONAL SPACE" title="Posts"/><div className="posts-layout"><form className="post-composer" onSubmit={submit}><div className="post-composer-heading"><div><p className="panel-kicker">NEW POST</p><h2>Share a thought</h2></div><span className="composer-status">Draft</span></div>{error && <ErrorLine>{error}</ErrorLine>}<Field label="Title" placeholder="Give your post a clear title" value={title} onChange={(event) => setTitle(event.target.value)} required/><TextArea label="Write" placeholder="Start writing…" value={body} onChange={(event) => setBody(event.target.value)} required rows={8}/><div className="composer-actions"><span>Visible only in your workspace</span><button className="button button-primary">Publish post</button></div></form><section className="post-panel"><div className="post-panel-heading"><div><p className="panel-kicker">YOUR WRITING</p><h2>Published</h2></div><span>{result?.pagination.total ?? 0} total</span></div>{loading ? <LoadingLine>Loading posts</LoadingLine> : <>{result?.data.length ? <div className="post-list">{result.data.map((post) => <article key={post._id}><div className="post-list-meta"><span>POST</span><time>{new Date(post.createdAt).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}</time></div><h3>{post.title}</h3><p>{post.body}</p></article>)}</div> : <p className="empty-state">Your published posts will appear here.</p>}{result && <Pagination pagination={result.pagination} onPage={setPage}/>}</>}</section></div></AppShell></Protected>; }
