/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminInterestsRouteImport } from './routes/admin.interests'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminNotesRouteImport } from './routes/admin.notes'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as NotesNewRouteImport } from './routes/notes.new'
import { Route as AdminUsersNewRouteImport } from './routes/admin.users.new'
import { Route as NotesIdEditRouteImport } from './routes/notes.$id.edit'
import { Route as AdminUsersIdEditRouteImport } from './routes/admin.users.$id.edit'
import { Route as AdminUsersIdPostsRouteImport } from './routes/admin.users.$id.posts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInterestsRoute = AdminInterestsRouteImport.update({
  id: '/admin/interests',
  path: '/admin/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotesRoute = AdminNotesRouteImport.update({
  id: '/admin/notes',
  path: '/admin/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNewRoute = NotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => NotesRoute,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminUsersRoute,
} as any)
const NotesIdEditRoute = NotesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => NotesRoute,
} as any)
const AdminUsersIdEditRoute = AdminUsersIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersIdPostsRoute = AdminUsersIdPostsRouteImport.update({
  id: '/$id/posts',
  path: '/$id/posts',
  getParentRoute: () => AdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRouteWithChildren
  '/posts': typeof PostsRoute
  '/register': typeof RegisterRoute
  '/admin/interests': typeof AdminInterestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/notes/new': typeof NotesNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/notes/$id/edit': typeof NotesIdEditRoute
  '/admin/users/$id/edit': typeof AdminUsersIdEditRoute
  '/admin/users/$id/posts': typeof AdminUsersIdPostsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRouteWithChildren
  '/posts': typeof PostsRoute
  '/register': typeof RegisterRoute
  '/admin/interests': typeof AdminInterestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/notes/new': typeof NotesNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/notes/$id/edit': typeof NotesIdEditRoute
  '/admin/users/$id/edit': typeof AdminUsersIdEditRoute
  '/admin/users/$id/posts': typeof AdminUsersIdPostsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRouteWithChildren
  '/posts': typeof PostsRoute
  '/register': typeof RegisterRoute
  '/admin/interests': typeof AdminInterestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/notes/new': typeof NotesNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/notes/$id/edit': typeof NotesIdEditRoute
  '/admin/users/$id/edit': typeof AdminUsersIdEditRoute
  '/admin/users/$id/posts': typeof AdminUsersIdPostsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notes'
    | '/posts'
    | '/register'
    | '/admin/interests'
    | '/admin/login'
    | '/admin/notes'
    | '/admin/overview'
    | '/admin/setup'
    | '/admin/users'
    | '/notes/new'
    | '/admin/users/new'
    | '/notes/$id/edit'
    | '/admin/users/$id/edit'
    | '/admin/users/$id/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notes'
    | '/posts'
    | '/register'
    | '/admin/interests'
    | '/admin/login'
    | '/admin/notes'
    | '/admin/overview'
    | '/admin/setup'
    | '/admin/users'
    | '/notes/new'
    | '/admin/users/new'
    | '/notes/$id/edit'
    | '/admin/users/$id/edit'
    | '/admin/users/$id/posts'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/notes'
    | '/posts'
    | '/register'
    | '/admin/interests'
    | '/admin/login'
    | '/admin/notes'
    | '/admin/overview'
    | '/admin/setup'
    | '/admin/users'
    | '/notes/new'
    | '/admin/users/new'
    | '/notes/$id/edit'
    | '/admin/users/$id/edit'
    | '/admin/users/$id/posts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRouteWithChildren
  PostsRoute: typeof PostsRoute
  RegisterRoute: typeof RegisterRoute
  AdminInterestsRoute: typeof AdminInterestsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotesRoute: typeof AdminNotesRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/interests': {
      id: '/admin/interests'
      path: '/admin/interests'
      fullPath: '/admin/interests'
      preLoaderRoute: typeof AdminInterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notes': {
      id: '/admin/notes'
      path: '/admin/notes'
      fullPath: '/admin/notes'
      preLoaderRoute: typeof AdminNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/new': {
      id: '/notes/new'
      path: '/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof NotesNewRouteImport
      parentRoute: typeof NotesRoute
    }
    '/admin/users/new': {
      id: '/admin/users/new'
      path: '/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/notes/$id/edit': {
      id: '/notes/$id/edit'
      path: '/$id/edit'
      fullPath: '/notes/$id/edit'
      preLoaderRoute: typeof NotesIdEditRouteImport
      parentRoute: typeof NotesRoute
    }
    '/admin/users/$id/edit': {
      id: '/admin/users/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/users/$id/edit'
      preLoaderRoute: typeof AdminUsersIdEditRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/$id/posts': {
      id: '/admin/users/$id/posts'
      path: '/$id/posts'
      fullPath: '/admin/users/$id/posts'
      preLoaderRoute: typeof AdminUsersIdPostsRouteImport
      parentRoute: typeof AdminUsersRoute
    }
  }
}

interface NotesRouteChildren {
  NotesNewRoute: typeof NotesNewRoute
  NotesIdEditRoute: typeof NotesIdEditRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesNewRoute: NotesNewRoute,
  NotesIdEditRoute: NotesIdEditRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminUsersIdEditRoute: typeof AdminUsersIdEditRoute
  AdminUsersIdPostsRoute: typeof AdminUsersIdPostsRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminUsersIdEditRoute: AdminUsersIdEditRoute,
  AdminUsersIdPostsRoute: AdminUsersIdPostsRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRouteWithChildren,
  PostsRoute: PostsRoute,
  RegisterRoute: RegisterRoute,
  AdminInterestsRoute: AdminInterestsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotesRoute: AdminNotesRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
